linters-settings:
  golint:
    min-confidence: 0
  misspell:
    locale: US
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

  gofumpt:
    # Select the Go version to target. The default is `1.15`.
    lang-version: "1.15"

    # Choose whether or not to use the extra rules that are disabled
    # by default
    extra-rules: false
  errcheck: